services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile

    container_name: next-prod

    ports:
      - '3000:3000'

    env_file:
      - web/.env.production

    restart: unless-stopped
