FROM node:22-alpine

RUN apk add --no-cache libc6-compat

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY eslint.config.mjs ./
COPY web ./web

WORKDIR /app/web

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "dev"]